// Run this ONCE to seed sample games into Firestore, then remove the call.
// Usage: import { seedGames } from './lib/seed'; seedGames();
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from './firebase';

const samples = [
  { sport:'Soccer',     format:'Co-ed 7v7',      level:'Casual-Competitive', when:'Tonight · 6:30 PM',    where:'Gibbons Park',        distance:2.1, duration:'75 mins', playersIn:10, playersNeeded:12, trust:96, hostName:'Jacob', hostMeta:'23 games hosted', initials:'JB', note:'Regular Western crowd with enough structure to feel like a real run, not chaos.',        organizerDescription:'We usually split into balanced sides after a five-minute warm-up and start on time. New players are welcome — arrive a bit early so teams can be set before kickoff.',  bring:'Dark + light shirt', vibe:'2 spots left', gradient:'linear-gradient(135deg,#0e7c66,#1d9f7d 68%,#6dcdb7)' },
  { sport:'Basketball', format:'Indoor 4s',       level:'Intermediate',       when:'Tonight · 8:00 PM',    where:'Campus Rec',           distance:1.2, duration:'60 mins', playersIn:8,  playersNeeded:10, trust:91, hostName:'Amir',  hostMeta:'11 games hosted', initials:'AM', note:'Short rotations, good pace, easy yes for players who want guaranteed minutes.',          organizerDescription:'Best for players comfortable with quick changes and calling their own fouls. Games move fast — bring water and show up ready to jump in.',                            bring:'Indoor shoes',       vibe:'2 spots left', gradient:'linear-gradient(135deg,#7a4dd1,#a06cf0 60%,#d0b4ff)' },
  { sport:'Volleyball', format:'Beach 4s',        level:'Beginner-Friendly',  when:'Tomorrow · 5:45 PM',   where:'Springbank',           distance:5.4, duration:'90 mins', playersIn:5,  playersNeeded:8,  trust:98, hostName:'Lena',  hostMeta:'18 games hosted', initials:'LN', note:'Sunset vibe, low pressure, ideal for players who want energy over elite skill.',          organizerDescription:'Great option if you want a social game first, competition second. We rotate partners every few sets — newer players are totally fine here.',                          bring:'Water + shades',     vibe:'3 spots left', gradient:'linear-gradient(135deg,#cc6d11,#ef9333 65%,#f6c173)' },
  { sport:'Tennis',     format:'Doubles ladder',  level:'Competitive',        when:'Tomorrow · 7:15 PM',   where:'North London Courts',  distance:7.2, duration:'80 mins', playersIn:6,  playersNeeded:8,  trust:93, hostName:'Maya',  hostMeta:'14 games hosted', initials:'MY', note:'Quick partner rotation with enough edge to attract players who want a serious hit.',     organizerDescription:'This ladder is for players who can hold a rally and want a sharper pace. We swap courts every 15–20 min based on wins. Cancel early if you cannot make it.',        bring:'Racket + balls',     vibe:'2 spots left', gradient:'linear-gradient(135deg,#1f6bde,#3f90ff 62%,#98c7ff)' },
  { sport:'Hockey',     format:'Shinny',           level:'Casual',             when:'Friday · 9:00 PM',     where:'East Lions Arena',     distance:9.4, duration:'70 mins', playersIn:11, playersNeeded:14, trust:89, hostName:'Chris', hostMeta:'31 games hosted', initials:'CH', note:'Late-night shinny with a dependable core group and room for more skaters.',              organizerDescription:'We usually have enough regulars for steady shifts but need extra skaters. Full gear expected. Goalies get priority confirmation.',                                    bring:'Full gear',           vibe:'3 spots left', gradient:'linear-gradient(135deg,#12445e,#1b6f91 60%,#7bc0dc)' },
  { sport:'Pickleball', format:'Open play',        level:'Casual',             when:'Today · 7:00 PM',      where:'Westmount',            distance:3.3, duration:'60 mins', playersIn:9,  playersNeeded:12, trust:95, hostName:'Nina',  hostMeta:'8 games hosted',  initials:'NN', note:'Great first swipe for new residents who want a friendly crowd and easy entry.',         organizerDescription:'Intentionally welcoming for first-timers — nobody will care if you are still learning. We rotate courts often and keep games balanced by experience.',               bring:'Paddle',              vibe:'3 spots left', gradient:'linear-gradient(135deg,#3d8b2d,#5aa540 60%,#a9de7d)' },
  { sport:'Ultimate',   format:'6v6',              level:'Casual-Competitive', when:'Thursday · 6:15 PM',   where:'UWO Alumni Field',     distance:2.8, duration:'85 mins', playersIn:9,  playersNeeded:12, trust:94, hostName:'Sean',  hostMeta:'16 games hosted', initials:'SN', note:'Spirit-first energy, but still enough pace to feel worth the run.',                  organizerDescription:'Expect a fun but organized run with mixed experience levels and quick resets between points. We self-officiate and keep the pace high.',                             bring:'Cleats',              vibe:'3 spots left', gradient:'linear-gradient(135deg,#8d2db6,#ba52d8 62%,#ebb2ff)' },
  { sport:'Badminton',  format:'Ladder doubles',   level:'Intermediate',       when:'Saturday · 1:00 PM',   where:'Bostwick YMCA',        distance:6.7, duration:'90 mins', playersIn:10, playersNeeded:12, trust:92, hostName:'Priya', hostMeta:'20 games hosted', initials:'PR', note:'High-energy doubles block with a near-full roster and quick turnaround between games.', organizerDescription:'The goal is constant play — we keep breaks short and move winners up the ladder. Indoor shoes are a must.',                                                           bring:'Racket + indoor shoes',vibe:'2 spots left', gradient:'linear-gradient(135deg,#8b520d,#c97a1a 58%,#f2bf67)' },
];

export async function seedGames() {
  const ref = collection(db, 'games');
  for (const g of samples) await addDoc(ref, { ...g, createdAt: serverTimestamp() });
  console.log('Seeded', samples.length, 'games into Firestore.');
}
